name: Build and Push Docker Images

on:
  push:
    # branches:
    #   - 'master'
    #   - 'main'
    # paths:
    #   - src/**

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      matrix:
        include:
          - context: ./src/node/addon/
            image_name: knightcrawler-addon
            platforms: linux/amd64,linux/arm64
          - context: ./src/node/addon-jackett/
            image_name: knightcrawler-addon-jackett
            platforms: linux/amd64,linux/arm64
          - context: ./src/node/consumer/
            image_name: knightcrawler-consumer
            platforms: linux/amd64,linux/arm64
          - context: ./src/producer/
            image_name: knightcrawler-producer
            platforms: linux/amd64,linux/arm64

    name: Build - ${{ matrix.image_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            nowaidavid/${{ matrix.image_name }}
          flavor: |
            latest=auto
          tags: |
            type=edge,branch=main,commit=${{ github.sha }}
            type=sha,commit=${{ github.sha }}
            
      - name: Build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          provenance: false
          tags: localhost:5000/dockle-examine-image:test
          platforms: ${{ matrix.platforms }}
       
      # - name: Build and push ${{ matrix.image_name }}
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ${{ matrix.context }}
      #     push: false
      #     load: true
      #     provenance: false
      #     tags: ${{ steps.docker-metadata.outputs.tags }}
      #     labels: ${{ steps.docker-metadata.outputs.labels }}
      #     platforms: ${{ matrix.platforms }}
       
      - name: Dockle - Examine Best Practices
        uses: davidjameshowell/dockle-action@a98f43d61714d99c87440a507c109a6f193bedff
        with:
          image: localhost:5000/dockle-examine-image:test\
          dockle-non-ssl: true
