name: Build Docker Images

on:
  push:
    # branches:
    #   - 'master'
    # paths:
    #   - src/**

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./src/node/addon/
            image_name: nowaidavid/knightcrawler-addon
            tag: nowaidavid/knightcrawler-addon:latest
          - context: ./src/node/addon-jackett/
            image_name: nowaidavid/knightcrawler-addon-jackett
            tag: nowaidavid/knightcrawler-addon-jackett:latest
          - context: ./src/node/consumer/
            image_name: nowaidavid/knightcrawler-consumer
            tag: nowaidavid/knightcrawler-consumer:latest
          - context: ./src/producer/
            image_name: nowaidavid/knightcrawler-producer
            tag: nowaidavid/knightcrawler-producer:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ matrix.image_name }}
          flavor: |
            latest=auto
          tags: |
            type=edge,branch=main,commit=${{ github.sha }}
            type=sha,commit=${{ github.sha }}
      - 
        name: Build and push ${{ matrix.tag }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64